### ISSUE TITLE
How can I display the years?

### ISSUE THREAD

**Issue by antonioj1015** [bastianallgeier/gantti#17]
How can I display the years wheter on top of the months or by the side of the month example: October/13 or October-13 or October 2013 ...

ThankS!!

**Comment by antonioj1015** [comment]
I got just added this line:

function name_year() {
    return strftime('%B %Y', $this->timestamp);
}

**Comment by niencynth** [comment]
@antonioj1015 

Can you tell me where to put that 'function name_year()'? Thanks!!

**Comment by MatthewSchenker** [comment]
I would also like to know how to display the year.  I see the above year function, but it is unclear where this belongs in the code.  Please re-open for an answer.

**Comment by antonioj1015** [comment]
Hi, look for it in the lib/calendar.php file, under the class CalendarMonth, just copy and paste the function after the function shortname(), and then in the lib/gantii.php look for:

$html[] = '&lt;li class=&quot;gantt-month&quot; style=&quot;width: ' . ($this-&gt;options['cellwidth'] \* $month-&gt;countDays()) . 'px&quot;&gt;&lt;strong ' . $cellstyle . '&gt;' . $month-&gt;name() . '&lt;/strong&gt;&lt;/li&gt;';

and replace with:

$html[] = '&lt;li class=&quot;gantt-month&quot; style=&quot;width: ' . ($this-&gt;options['cellwidth'] \* $month-&gt;countDays()) . 'px&quot;&gt;&lt;strong ' . $cellstyle . '&gt;' . $month-&gt;name_year() . '&lt;/strong&gt;&lt;/li&gt;';

If you want to print aditional date statements look into http://php.net/strftime

**Comment by MatthewSchenker** [comment]
Thanks antonioj1015.  I was putting this as a new year(), which is why it didn't work before.  It has to go into the CalendarMonth class instead.

Works great now.

I would suggest having years included by default.
