### ISSUE TITLE
Add year to months ex. December 2013

### ISSUE THREAD

**Issue by niencynth** [bastianallgeier/gantti#20]
there's a closed issue about this and the guy said just add 

function name_year() {
return strftime('%B %Y', $this->timestamp);
}

but I don't know where to put that.

**Comment by niencynth** [comment]
oh sorry i just have to put '%Y' in functions not the whole line.

**Comment by antonioj1015** [comment]
<p>Hi, look for it in the lib/calendar.php file, under the class CalendarMonth, just copy and paste the function after the function shortname(), and then in the lib/gantii.php look for:</p>

<p>$html[] = '&lt;li class="gantt-month" style="width: ' . ($this-&gt;options['cellwidth'] * $month-&gt;countDays()) . 'px"&gt;&lt;strong ' . $cellstyle . '&gt;' . $month-&gt;name() . '&lt;/strong&gt;&lt;/li&gt;';</p>

<p>and replace with:</p>

<p>$html[] = '&lt;li class="gantt-month" style="width: ' . ($this-&gt;options['cellwidth'] * $month-&gt;countDays()) . 'px"&gt;&lt;strong ' . $cellstyle . '&gt;' . $month-&gt;name_year() . '&lt;/strong&gt;&lt;/li&gt;';</p>

<p>If you want to print aditional date statements look into <a href="http://php.net/strftime">http://php.net/strftime</a></p>
